/**
 * Mock Course Data
 *
 * Static course data for development.
 * Will be replaced with CMS integration.
 */

import type { CourseDetail, CourseSummary } from './types';

export const MOCK_COURSES: CourseDetail[] = [
  {
    slug: 'solana-fundamentals',
    title: 'Solana Fundamentals',
    description: 'Master the basics of Solana blockchain development. Learn accounts, transactions, and the runtime.',
    longDescription: `This comprehensive course covers everything you need to know to start building on Solana. 
    
You'll learn about Solana's unique architecture, including its account model, transaction processing, and runtime environment. By the end, you'll understand how to read and write data on-chain, create and manage accounts, and build your first Solana program.

Perfect for developers coming from other blockchains or new to Web3 entirely.`,
    thumbnailUrl: '/images/courses/solana-fundamentals.jpg',
    difficulty: 'beginner',
    track: 'core',
    lessonCount: 12,
    duration: 180,
    xpReward: 500,
    creatorName: 'Superteam',
    creatorAvatar: '/images/avatars/superteam.png',
    creatorBio: 'Superteam is a community-driven organization supporting Solana builders worldwide.',
    enrolledCount: 2500,
    rating: 4.8,
    tags: ['solana', 'blockchain', 'accounts', 'transactions'],
    publishedAt: new Date('2025-01-15'),
    featured: true,
    prerequisites: ['Basic programming knowledge', 'Familiarity with command line'],
    learningObjectives: [
      'Understand Solana\'s account model',
      'Create and manage Solana accounts',
      'Build and sign transactions',
      'Deploy your first program',
    ],
    lessons: [
      { id: 'intro', title: 'Introduction to Solana', type: 'video', duration: 15, xpReward: 25, order: 1 },
      { id: 'architecture', title: 'Solana Architecture Overview', type: 'article', duration: 20, xpReward: 30, order: 2 },
      { id: 'accounts-101', title: 'Understanding Accounts', type: 'video', duration: 18, xpReward: 35, order: 3 },
      { id: 'accounts-challenge', title: 'Account Challenge', type: 'challenge', duration: 25, xpReward: 50, order: 4 },
      { id: 'transactions', title: 'Building Transactions', type: 'video', duration: 20, xpReward: 35, order: 5 },
      { id: 'signing', title: 'Transaction Signing', type: 'article', duration: 15, xpReward: 25, order: 6 },
      { id: 'tx-challenge', title: 'Transaction Challenge', type: 'challenge', duration: 30, xpReward: 60, order: 7 },
      { id: 'programs-intro', title: 'Introduction to Programs', type: 'video', duration: 15, xpReward: 30, order: 8 },
      { id: 'hello-world', title: 'Hello World Program', type: 'challenge', duration: 40, xpReward: 80, order: 9 },
      { id: 'pda', title: 'Program Derived Addresses', type: 'video', duration: 20, xpReward: 40, order: 10 },
      { id: 'pda-challenge', title: 'PDA Challenge', type: 'challenge', duration: 35, xpReward: 70, order: 11 },
      { id: 'conclusion', title: 'Next Steps', type: 'article', duration: 10, xpReward: 20, order: 12 },
    ],
  },
  {
    slug: 'anchor-bootcamp',
    title: 'Anchor Framework Bootcamp',
    description: 'Build Solana programs with Anchor. From setup to deployment in one comprehensive course.',
    longDescription: `Anchor is the most popular framework for building Solana programs. This bootcamp takes you from zero to deploying production-ready programs.

You'll learn how to structure Anchor projects, define accounts and instructions, handle errors, write tests, and deploy to devnet and mainnet.

Includes hands-on challenges where you'll build real programs including a token swap, NFT minter, and DAO voting system.`,
    thumbnailUrl: '/images/courses/anchor-bootcamp.jpg',
    difficulty: 'intermediate',
    track: 'core',
    lessonCount: 15,
    duration: 300,
    xpReward: 800,
    creatorName: 'AnchorLabs',
    creatorAvatar: '/images/avatars/anchorlabs.png',
    creatorBio: 'Core contributors to the Anchor framework and Solana ecosystem.',
    enrolledCount: 1800,
    rating: 4.9,
    tags: ['anchor', 'rust', 'programs', 'smart-contracts'],
    publishedAt: new Date('2025-02-01'),
    featured: true,
    prerequisites: ['Solana Fundamentals course', 'Basic Rust knowledge'],
    learningObjectives: [
      'Set up Anchor development environment',
      'Define program accounts and instructions',
      'Implement access control and validation',
      'Write comprehensive tests',
      'Deploy to devnet and mainnet',
    ],
    lessons: [
      { id: 'setup', title: 'Environment Setup', type: 'video', duration: 20, xpReward: 30, order: 1 },
      { id: 'project-structure', title: 'Anchor Project Structure', type: 'article', duration: 15, xpReward: 25, order: 2 },
      { id: 'first-program', title: 'Your First Anchor Program', type: 'challenge', duration: 35, xpReward: 70, order: 3 },
      { id: 'accounts', title: 'Account Definitions', type: 'video', duration: 25, xpReward: 40, order: 4 },
      { id: 'constraints', title: 'Account Constraints', type: 'video', duration: 20, xpReward: 35, order: 5 },
      { id: 'constraints-challenge', title: 'Constraints Challenge', type: 'challenge', duration: 30, xpReward: 60, order: 6 },
      { id: 'errors', title: 'Error Handling', type: 'article', duration: 15, xpReward: 25, order: 7 },
      { id: 'testing', title: 'Testing with Bankrun', type: 'video', duration: 25, xpReward: 45, order: 8 },
      { id: 'test-challenge', title: 'Testing Challenge', type: 'challenge', duration: 40, xpReward: 80, order: 9 },
      { id: 'token-swap', title: 'Build: Token Swap', type: 'challenge', duration: 60, xpReward: 100, order: 10 },
      { id: 'cpis', title: 'Cross-Program Invocations', type: 'video', duration: 20, xpReward: 40, order: 11 },
      { id: 'nft-minter', title: 'Build: NFT Minter', type: 'challenge', duration: 50, xpReward: 90, order: 12 },
      { id: 'deployment', title: 'Deployment Guide', type: 'article', duration: 20, xpReward: 35, order: 13 },
      { id: 'dao-voting', title: 'Build: DAO Voting', type: 'challenge', duration: 55, xpReward: 95, order: 14 },
      { id: 'best-practices', title: 'Best Practices & Security', type: 'video', duration: 25, xpReward: 50, order: 15 },
    ],
  },
  {
    slug: 'token-2022-deep-dive',
    title: 'Token-2022 Deep Dive',
    description: 'Master Token-2022 extensions: transfer fees, permanent delegates, soulbound tokens, and more.',
    longDescription: `Token-2022 introduces powerful new capabilities to Solana tokens. This course covers every extension in depth.

Learn to create tokens with transfer fees, permanent delegates for soulbound tokens, confidential transfers, and more. Real-world examples include building loyalty points, game currencies, and compliant security tokens.`,
    thumbnailUrl: '/images/courses/token-2022.jpg',
    difficulty: 'advanced',
    track: 'defi',
    lessonCount: 10,
    duration: 200,
    xpReward: 600,
    creatorName: 'TokenMaster',
    creatorAvatar: '/images/avatars/tokenmaster.png',
    creatorBio: 'Token specialist building next-gen tokenomics on Solana.',
    enrolledCount: 950,
    rating: 4.7,
    tags: ['token-2022', 'spl-token', 'extensions', 'defi'],
    publishedAt: new Date('2025-03-10'),
    featured: true,
    prerequisites: ['Anchor Framework Bootcamp', 'Understanding of SPL tokens'],
    learningObjectives: [
      'Create tokens with Token-2022',
      'Implement transfer fees',
      'Build soulbound tokens',
      'Use confidential transfers',
    ],
    lessons: [
      { id: 'intro', title: 'Token-2022 Overview', type: 'video', duration: 15, xpReward: 25, order: 1 },
      { id: 'extensions', title: 'Extension Architecture', type: 'article', duration: 20, xpReward: 30, order: 2 },
      { id: 'transfer-fees', title: 'Transfer Fees', type: 'video', duration: 25, xpReward: 45, order: 3 },
      { id: 'fees-challenge', title: 'Transfer Fees Challenge', type: 'challenge', duration: 35, xpReward: 70, order: 4 },
      { id: 'permanent-delegate', title: 'Permanent Delegate', type: 'video', duration: 20, xpReward: 40, order: 5 },
      { id: 'soulbound', title: 'Building Soulbound Tokens', type: 'challenge', duration: 40, xpReward: 80, order: 6 },
      { id: 'non-transferable', title: 'Non-Transferable Extension', type: 'video', duration: 15, xpReward: 30, order: 7 },
      { id: 'metadata', title: 'Token Metadata Pointer', type: 'article', duration: 20, xpReward: 35, order: 8 },
      { id: 'confidential', title: 'Confidential Transfers', type: 'video', duration: 30, xpReward: 55, order: 9 },
      { id: 'final-project', title: 'Final Project: XP Token', type: 'challenge', duration: 60, xpReward: 120, order: 10 },
    ],
  },
  {
    slug: 'nft-marketplace',
    title: 'Build an NFT Marketplace',
    description: 'Create a full-featured NFT marketplace from scratch using Metaplex and Anchor.',
    longDescription: `Build a production-ready NFT marketplace step by step. Learn to mint, list, buy, and auction NFTs.

This project-based course covers Metaplex protocols, royalty enforcement, compressed NFTs, and marketplace economics. You'll deploy a working marketplace to devnet.`,
    thumbnailUrl: '/images/courses/nft-marketplace.jpg',
    difficulty: 'advanced',
    track: 'nft',
    lessonCount: 14,
    duration: 280,
    xpReward: 750,
    creatorName: 'NFTBuilder',
    creatorAvatar: '/images/avatars/nftbuilder.png',
    creatorBio: 'Building the future of digital ownership on Solana.',
    enrolledCount: 1200,
    rating: 4.6,
    tags: ['nft', 'metaplex', 'marketplace', 'bubblegum'],
    publishedAt: new Date('2025-02-20'),
    featured: false,
    prerequisites: ['Anchor Framework Bootcamp'],
    learningObjectives: [
      'Create NFT collections with Metaplex',
      'Build listing and auction mechanics',
      'Implement royalty enforcement',
      'Deploy a working marketplace',
    ],
    lessons: [
      { id: 'overview', title: 'Marketplace Architecture', type: 'video', duration: 20, xpReward: 35, order: 1 },
      { id: 'metaplex', title: 'Metaplex Protocol', type: 'article', duration: 25, xpReward: 40, order: 2 },
      { id: 'minting', title: 'NFT Minting', type: 'video', duration: 20, xpReward: 35, order: 3 },
      { id: 'mint-challenge', title: 'Minting Challenge', type: 'challenge', duration: 30, xpReward: 60, order: 4 },
      { id: 'collections', title: 'Collections & Verification', type: 'video', duration: 20, xpReward: 35, order: 5 },
      { id: 'listings', title: 'Building Listings', type: 'video', duration: 25, xpReward: 45, order: 6 },
      { id: 'listing-challenge', title: 'Listing Challenge', type: 'challenge', duration: 35, xpReward: 70, order: 7 },
      { id: 'purchasing', title: 'Purchase Flow', type: 'video', duration: 20, xpReward: 40, order: 8 },
      { id: 'purchase-challenge', title: 'Purchase Challenge', type: 'challenge', duration: 35, xpReward: 70, order: 9 },
      { id: 'auctions', title: 'Auction Mechanics', type: 'video', duration: 25, xpReward: 50, order: 10 },
      { id: 'auction-challenge', title: 'Auction Challenge', type: 'challenge', duration: 40, xpReward: 80, order: 11 },
      { id: 'royalties', title: 'Royalty Enforcement', type: 'article', duration: 15, xpReward: 30, order: 12 },
      { id: 'compressed', title: 'Compressed NFTs', type: 'video', duration: 25, xpReward: 50, order: 13 },
      { id: 'deployment', title: 'Marketplace Deployment', type: 'challenge', duration: 45, xpReward: 90, order: 14 },
    ],
  },
  {
    slug: 'defi-primitives',
    title: 'DeFi Primitives on Solana',
    description: 'Learn AMMs, lending protocols, and yield aggregators. Build DeFi from scratch.',
    longDescription: `Understand and build the core primitives powering Solana DeFi. This course covers constant product AMMs, lending pool mechanics, and composable yield strategies.

You'll implement a simple AMM, build a lending protocol, and create a yield optimizer. Math-heavy but practical.`,
    thumbnailUrl: '/images/courses/defi-primitives.jpg',
    difficulty: 'advanced',
    track: 'defi',
    lessonCount: 12,
    duration: 240,
    xpReward: 700,
    creatorName: 'DeFiDev',
    creatorAvatar: '/images/avatars/defidev.png',
    creatorBio: 'DeFi protocol developer and security researcher.',
    enrolledCount: 800,
    rating: 4.8,
    tags: ['defi', 'amm', 'lending', 'yield'],
    publishedAt: new Date('2025-03-01'),
    featured: false,
    prerequisites: ['Token-2022 Deep Dive', 'Strong math background'],
    learningObjectives: [
      'Implement constant product AMM',
      'Build lending pool mechanics',
      'Create yield optimization strategies',
      'Handle complex DeFi math on-chain',
    ],
    lessons: [
      { id: 'defi-intro', title: 'DeFi on Solana', type: 'video', duration: 20, xpReward: 35, order: 1 },
      { id: 'amm-math', title: 'AMM Mathematics', type: 'article', duration: 25, xpReward: 45, order: 2 },
      { id: 'constant-product', title: 'Constant Product Formula', type: 'video', duration: 20, xpReward: 40, order: 3 },
      { id: 'amm-build', title: 'Build: Simple AMM', type: 'challenge', duration: 50, xpReward: 100, order: 4 },
      { id: 'lending-intro', title: 'Lending Protocols', type: 'video', duration: 20, xpReward: 35, order: 5 },
      { id: 'interest-rates', title: 'Interest Rate Models', type: 'article', duration: 25, xpReward: 45, order: 6 },
      { id: 'lending-build', title: 'Build: Lending Pool', type: 'challenge', duration: 55, xpReward: 110, order: 7 },
      { id: 'liquidations', title: 'Liquidation Mechanics', type: 'video', duration: 20, xpReward: 40, order: 8 },
      { id: 'liquidation-challenge', title: 'Liquidation Challenge', type: 'challenge', duration: 40, xpReward: 80, order: 9 },
      { id: 'yield-strategies', title: 'Yield Strategies', type: 'video', duration: 25, xpReward: 50, order: 10 },
      { id: 'yield-optimizer', title: 'Build: Yield Optimizer', type: 'challenge', duration: 50, xpReward: 95, order: 11 },
      { id: 'security', title: 'DeFi Security Considerations', type: 'article', duration: 20, xpReward: 40, order: 12 },
    ],
  },
  {
    slug: 'solana-gaming',
    title: 'Game Development on Solana',
    description: 'Build on-chain games with session keys, compressed state, and real-time updates.',
    longDescription: `Create performant blockchain games on Solana. Learn session keys for seamless UX, state compression for cheap storage, and patterns for real-time gameplay.

Build a complete game with inventory, achievements, and leaderboards.`,
    thumbnailUrl: '/images/courses/solana-gaming.jpg',
    difficulty: 'intermediate',
    track: 'gaming',
    lessonCount: 11,
    duration: 220,
    xpReward: 650,
    creatorName: 'GameDev Sol',
    creatorAvatar: '/images/avatars/gamedev.png',
    creatorBio: 'Game developer bringing AAA experiences to Web3.',
    enrolledCount: 650,
    rating: 4.5,
    tags: ['gaming', 'session-keys', 'compression', 'real-time'],
    publishedAt: new Date('2025-03-15'),
    featured: false,
    prerequisites: ['Anchor Framework Bootcamp'],
    learningObjectives: [
      'Implement session keys for smooth UX',
      'Use state compression for game data',
      'Build real-time game mechanics',
      'Create on-chain leaderboards',
    ],
    lessons: [
      { id: 'gaming-intro', title: 'Gaming on Solana', type: 'video', duration: 20, xpReward: 35, order: 1 },
      { id: 'session-keys', title: 'Session Keys', type: 'video', duration: 25, xpReward: 45, order: 2 },
      { id: 'session-challenge', title: 'Session Keys Challenge', type: 'challenge', duration: 35, xpReward: 70, order: 3 },
      { id: 'compression', title: 'State Compression', type: 'video', duration: 25, xpReward: 50, order: 4 },
      { id: 'compression-challenge', title: 'Compression Challenge', type: 'challenge', duration: 35, xpReward: 70, order: 5 },
      { id: 'inventory', title: 'Inventory Systems', type: 'video', duration: 20, xpReward: 40, order: 6 },
      { id: 'inventory-challenge', title: 'Inventory Challenge', type: 'challenge', duration: 40, xpReward: 80, order: 7 },
      { id: 'achievements', title: 'Achievement System', type: 'video', duration: 15, xpReward: 30, order: 8 },
      { id: 'leaderboards', title: 'On-chain Leaderboards', type: 'video', duration: 20, xpReward: 40, order: 9 },
      { id: 'leaderboard-challenge', title: 'Leaderboard Challenge', type: 'challenge', duration: 35, xpReward: 70, order: 10 },
      { id: 'final-game', title: 'Final Project: Complete Game', type: 'challenge', duration: 60, xpReward: 120, order: 11 },
    ],
  },
  {
    slug: 'dao-governance',
    title: 'DAO Governance Systems',
    description: 'Build governance systems with SPL Governance and custom voting mechanisms.',
    longDescription: `Design and implement DAO governance on Solana. Learn SPL Governance, custom voting systems, and treasury management.

Build a complete DAO with proposal creation, voting, and automatic execution.`,
    thumbnailUrl: '/images/courses/dao-governance.jpg',
    difficulty: 'intermediate',
    track: 'dao',
    lessonCount: 9,
    duration: 180,
    xpReward: 550,
    creatorName: 'DAOArchitect',
    creatorAvatar: '/images/avatars/daoarchitect.png',
    creatorBio: 'Building decentralized coordination tools.',
    enrolledCount: 450,
    rating: 4.4,
    tags: ['dao', 'governance', 'voting', 'treasury'],
    publishedAt: new Date('2025-03-20'),
    featured: false,
    prerequisites: ['Anchor Framework Bootcamp'],
    learningObjectives: [
      'Understand SPL Governance',
      'Build custom voting mechanisms',
      'Implement treasury management',
      'Create proposal systems',
    ],
    lessons: [
      { id: 'dao-intro', title: 'DAOs on Solana', type: 'video', duration: 20, xpReward: 35, order: 1 },
      { id: 'spl-governance', title: 'SPL Governance Overview', type: 'article', duration: 25, xpReward: 45, order: 2 },
      { id: 'realms', title: 'Realms Integration', type: 'video', duration: 20, xpReward: 40, order: 3 },
      { id: 'voting', title: 'Voting Mechanisms', type: 'video', duration: 25, xpReward: 50, order: 4 },
      { id: 'voting-challenge', title: 'Custom Voting Challenge', type: 'challenge', duration: 40, xpReward: 80, order: 5 },
      { id: 'proposals', title: 'Proposal System', type: 'video', duration: 20, xpReward: 40, order: 6 },
      { id: 'proposal-challenge', title: 'Proposal Challenge', type: 'challenge', duration: 35, xpReward: 70, order: 7 },
      { id: 'treasury', title: 'Treasury Management', type: 'video', duration: 20, xpReward: 40, order: 8 },
      { id: 'final-dao', title: 'Final Project: Complete DAO', type: 'challenge', duration: 55, xpReward: 110, order: 9 },
    ],
  },
  {
    slug: 'web3-frontend',
    title: 'Web3 Frontend Development',
    description: 'Build beautiful dApp frontends with Next.js, Wallet Adapter, and TanStack Query.',
    longDescription: `Create production-ready dApp frontends. Learn wallet connection, transaction building, state management, and real-time updates.

Build a complete frontend for a DeFi protocol with portfolio tracking and transaction history.`,
    thumbnailUrl: '/images/courses/web3-frontend.jpg',
    difficulty: 'beginner',
    track: 'core',
    lessonCount: 10,
    duration: 160,
    xpReward: 450,
    creatorName: 'FrontendPro',
    creatorAvatar: '/images/avatars/frontendpro.png',
    creatorBio: 'Full-stack developer specializing in Web3 UX.',
    enrolledCount: 1100,
    rating: 4.7,
    tags: ['frontend', 'nextjs', 'wallet-adapter', 'react'],
    publishedAt: new Date('2025-01-25'),
    featured: false,
    prerequisites: ['React basics', 'TypeScript knowledge'],
    learningObjectives: [
      'Connect wallets with Wallet Adapter',
      'Build and send transactions',
      'Manage async state with TanStack Query',
      'Display real-time blockchain data',
    ],
    lessons: [
      { id: 'frontend-intro', title: 'Web3 Frontend Overview', type: 'video', duration: 15, xpReward: 25, order: 1 },
      { id: 'wallet-setup', title: 'Wallet Adapter Setup', type: 'video', duration: 20, xpReward: 35, order: 2 },
      { id: 'wallet-challenge', title: 'Wallet Connection Challenge', type: 'challenge', duration: 25, xpReward: 50, order: 3 },
      { id: 'transactions', title: 'Building Transactions', type: 'video', duration: 20, xpReward: 40, order: 4 },
      { id: 'tx-challenge', title: 'Transaction Challenge', type: 'challenge', duration: 30, xpReward: 60, order: 5 },
      { id: 'tanstack', title: 'TanStack Query for Web3', type: 'video', duration: 20, xpReward: 40, order: 6 },
      { id: 'query-challenge', title: 'Query Challenge', type: 'challenge', duration: 25, xpReward: 50, order: 7 },
      { id: 'real-time', title: 'Real-time Updates', type: 'video', duration: 15, xpReward: 30, order: 8 },
      { id: 'portfolio', title: 'Build: Portfolio Tracker', type: 'challenge', duration: 35, xpReward: 70, order: 9 },
      { id: 'best-practices', title: 'Frontend Best Practices', type: 'article', duration: 15, xpReward: 30, order: 10 },
    ],
  },
];

/**
 * Get course summaries (without full lesson details)
 */
export function getCourseSummaries(): CourseSummary[] {
  return MOCK_COURSES.map(({ lessons: _lessons, longDescription: _long, prerequisites: _pre, learningObjectives: _obj, creatorBio: _bio, ...summary }) => summary);
}

/**
 * Get all unique tags from courses
 */
export function getAllTags(): string[] {
  const tagSet = new Set<string>();
  MOCK_COURSES.forEach((course) => {
    course.tags.forEach((tag) => tagSet.add(tag));
  });
  return Array.from(tagSet).sort();
}
